[project]
name = "ShamAPI"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dashvvood", email = "780966523@qq.com" }
]
requires-python = ">=3.12"
# 基础依赖
dependencies = [
    "tqdm",
    "elinor",
    "loguru",
    "pandas",
    "pyyaml",
    "ipykernel",
    "omegaconf",
    "ipywidgets",
    "concurrent-log-handler",
]


# 默认添加的额外依赖组
[tool.uv]
default-groups = ["dev"]

# 依赖组所需的特殊Python版本,要求比上方的基础依赖更高的Python版本时需要单独指定
[tool.uv.dependency-groups]
whisper = {requires-python = ">=3.12"}

[dependency-groups]
dev = [
    "pytest",
]

audio = [
    "audioread",
    "librosa",
]

web = [
    "aiohttp",
    "fastapi",
    "gunicorn",
    "requests",
    "uvicorn",
]

qwen = [
    {include-group = "audio"},
    {include-group = "web"},
    "accelerate>=1.11.0",
    "modelscope>=1.35.2",
    "qwen-omni-utils>=0.0.8",
    "qwen-vl-utils>=0.0.14",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.57.1",
]

whisper = [
    {include-group = "audio"},
    {include-group = "web"},
    # "ctranslate2==4.5.0",
    "openai-whisper>=20250625",
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "torchvision==0.23.0",
    "whisperx==3.7.4",
]

rtmlib = [
    {include-group = "web"},
    "moviepy>=1.0.3",
    "onnxruntime-gpu>=1.23.2",
    "opencv-contrib-python>=4.12.0.88",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
    "rtmlib>=0.0.15",
]

vllm = [
    "modelscope>=1.35.1",
    "vllm>=0.11.0",
]

