# case
# useless if using gunicorn with uvicorn workers
app:
  name: rtmlib
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: True
# esac

model:
  device: "cuda"  # cpu, cuda, mps
  backend: "onnxruntime"  # opencv, onnxruntime, openvino
  to_openpose: False
  mode: 'performance'  # 'performance', 'lightweight', 'balanced'. Default: 'balanced'

log:
  level: "INFO"
  sink: "logs/rtmlib.log"
  rotation: "10 MB"
  retention: "7 days"
  encoding : "utf-8"
  enqueue: True
  backtrace: True
  diagnose: False
  colorize: True
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"


