# case
# useless if using gunicorn with uvicorn workers
app:
  name: qwen3
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: True

model:
  repo_id: "Qwen/Qwen3-4B-Instruct-2507"
  model_dir: "./cache/Qwen3-4B-Instruct-2507"
  device_map: "auto"  # cpu, cuda, mps
  torch_type: bfloat16

log:
  level: "INFO"
  sink: "log/qwen3.log"
  rotation: "10 MB"
  retention: "7 days"
  encoding : "utf-8"
  enqueue: True
  backtrace: True
  diagnose: False
  colorize: True
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {process} | {message}"
